service: fastapi-lambda

provider:
  name: aws
  runtime: python3.11
  region: eu-north-1

package:
  artifact: function.zip

functions:
  api:
    handler: main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY