name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies and build function.zip
        run: |
          mkdir -p build
          pip install --target build -r requirements.txt
          cp main.py build/
          cd build
          zip -r ../function.zip .
          cd ..
          rm -rf build

      - name: Check that function.zip exists
        run: |
          ls -lh function.zip
          unzip -l function.zip

      - name: Set up Node.js for Serverless
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Serverless CLI (v3 – no login required)
        run: npm install -g serverless@3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to AWS Lambda
        run: serverless deploy

      - name: Show deployed endpoint
        run: serverless info